### ISSUE TITLE
What is a chinese software cup

### ISSUE THREAD

**Issue by LRCZCM** [fafa-junhe/LoongArchAi#1]
There will be many regrets in a person's life. If you lose something, you can never find it again. However, instead of lamenting that time has passed and you can't turn back, and being miserable, it is better to grasp everything in your hands and not let them become the next regret. Helen Keller was smart and studious, but God did not give him the health of a normal person. This is not only a pity, but also a tragedy. However, he did things that ordinary people could not do with his strong perseverance. It was the philosophical flaws that inspired her to strive for success. Sometimes, the loss of something will make you cherish everything you have now. It is not terrible to have regrets. The terrible thing is that you can't let go of those obsessions and always indulge in the sorrow of the past. You will never recover. As long as you look at it more openly, you will understand that God closes a door for you and opens another door for you. Only by walking out of regret can you prevent regrets from happening again. Losing is certainly a regret, and it is also a regret that you want to get something but cannot get it temporarily. If you don't dredge it in time, it will accumulate in your heart and become a kind of depression. If you don't get out of the painful torment in time, you will be burned by the fire of pain. For this situation, the best way is to transform this regret into a motivation. Let it become the driving force for the next goal. Let your new dream come true.
For a long time, many of us have regarded regret as a tragedy that makes people sigh. But who would have thought that regret would produce a special power? It can even become a stepping stone to success.
A young man who was determined to take the postgraduate entrance examination of the People's Bank of China almost read the three volumes of "Chinese Financial History". Unfortunately, he failed to pass the exam repeatedly. But he did not get depressed. He always believed: Lose in the east, you will definitely gain in the west. During this period, some friends kept asking him for advice on some ancient coins. At first, he explained carefully and patiently. Later, when he saw more people asking, he wrote the book "Explanation of Chinese Coins in Successive Dynasties". Once this book was published, it caused a sensation across the country and became famous.
It is a pity that an unattainable dream is difficult to realize, it is a pity to make an irreparable mistake, it is a pity to miss a rare opportunity, but eight out of ten things in life are not as good as what you want. As long as you move forward bravely, if you miss the scenery here, there will be scenery elsewhere. Tagore has a famous saying: When you cry for missing the sun, you will also miss the stars.
Look at regret from another angle, regret is also a kind of beauty. It's just that this kind of beauty is bleak and gorgeous. Like the Venus with broken arms. If everything in this world is perfect, there is no real perfection. It is precisely because of these imperfections that other perfections can be set off. More importantly, regret will give birth to an upward force. Can't we say that regret is also a kind of beauty.
Turn a corner, the world will be bigger, give up a regret, and you will definitely create more glory than regret.

**Comment by fafa-junhe** [comment]
Thank you
